Project KHCN_SCHEMA {
    database_type: 'Oracle'
note: '''
# Ecommerce Database
**markdown content here**
'''
}


Table KHCN_THUYET_MINH_DE_TAI as TMDT {
  MA_THUYET_MINH_DE_TAI nvarchar(8) [pk]
  SHCC   nvarchar2(10) 
	MA_SO_DE_TAI   nvarchar2(20) 
	NGAY_NHAN_HO_SO number(200) 
	TEN_DE_TAI_VN   nvarchar2(2000) 
	TEN_DE_TAI_EN   nvarchar2(2000) 
	FK_CAP_DE_TAI   nvarchar2(2) 
	FL_LOAI_DE_TAI   nvarchar2(2) 
	HUONG_DE_TAI   nvarchar2(2000) 
	KEYWORDS   nvarchar2(1000) 
	CHUYEN_NGANH_HEP   nvarchar2(500) 
	THOI_GIAN_THUC_HIEN number 
	FK_LOAI_HINH_NC   nvarchar2(2) 
	TONG_KINH_PHI number 
	KINH_PHI_TU_DHQG number 
	KINH_PHI_HUY_DONG number 
	HD_VON_TU_CO number 
	HD_KHAC number 
	NGUON_KP_KHAC number 
	FK_CHU_NHIEM_DT   nvarchar2(6) 
	CNDT_HH_HV_HO_TEN   nvarchar2(100) 
	CNDT_NGAY_SINH number(200) 
	CNDT_PHAI   nvarchar2(2) 
	CNDT_SO_CMND   nvarchar2(12) 
	CNDT_NGAY_CAP number(200) 
	CNDT_NOI_CAP   nvarchar2(2) 
	CNDT_MS_THUE   nvarchar2(10) 
	CNDT_SO_TAI_KHOAN   nvarchar2(30) 
	CNDT_NGAN_HANG   nvarchar2(400) 
	CNDT_DIA_CHI_CQ   nvarchar2(400) 
	CNDT_DIEN_THOAI   nvarchar2(100) 
	CNDT_EMAIL   nvarchar2(100) 
	TOM_TAT_HD_NC clob 
	FK_CQ_CHU_TRI   nvarchar2(5) 
	CQCT_TEN_CO_QUAN   nvarchar2(1000) 
	CQCT_HO_TEN_TT   nvarchar2(100) 
	CQCT_DIEN_THOAI   nvarchar2(100) 
	CQCT_FAX   nvarchar2(50) 
	CQCT_DIA_CHI   nvarchar2(400) 
	CQCT_EMAIL   nvarchar2(100) 
	CQCT_SO_TAI_KHOAN   nvarchar2(30) 
	CQCT_KHO_BAC   nvarchar2(400) 
	FK_CQ_PHOI_HOP_1   nvarchar2(5) 
	CQPH1_TEN_CO_QUAN   nvarchar2(1000) 
	CQPH1_HO_TEN_TT   nvarchar2(100) 
	CQPH1_DIEN_THOAI   nvarchar2(100) 
	CQPH1_FAX   nvarchar2(50) 
	CQPH1_DIA_CHI   nvarchar2(400) 
	CQPH1_EMAIL   nvarchar2(100) 
	CQPH1_SO_TAI_KHOAN   nvarchar2(30) 
	CQPH1_KHO_BAC   nvarchar2(400) 
	FK_CQ_PHOI_HOP_2   nvarchar2(5) 
	CQPH2_TEN_CO_QUAN   nvarchar2(1000) 
	CQPH2_HO_TEN_TT   nvarchar2(100) 
	CQPH2_DIEN_THOAI   nvarchar2(100) 
	CQPH2_FAX   nvarchar2(50) 
	CQPH2_DIA_CHI   nvarchar2(400) 
	CQPH2_EMAIL   nvarchar2(100) 
	CQPH2_SO_TAI_KHOAN   nvarchar2(30) 
	CQPH2_KHO_BAC   nvarchar2(400) 
	TQ_TINH_HINH_NC_LINK   nvarchar2(200) 
	Y_TUONG_KH_LINK   nvarchar2(200) 
	KQ_NC_SO_KHOI_LINK   nvarchar2(200) 
	TAI_LIEU_TK_LINK   nvarchar2(200) 
	MUC_TIEU_NC_EN_LINK   nvarchar2(200) 
	MUC_TIEU_NC_VN_LINK   nvarchar2(200) 
	NOI_DUNG_NC_LINK   nvarchar2(200) 
	PA_PHOI_HOP_LINK   nvarchar2(200) 
	KN_UD_KQNC_LINK   nvarchar2(200) 
	GHI_CHU clob 
	FK_DONG_CHU_NHIEM_DT   nvarchar2(6) 
	DCNDT_HH_HV_HO_TEN   nvarchar2(100) 
	DCNDT_NGAY_SINH number(200) 
	DCNDT_PHAI   nvarchar2(2) 
	DCNDT_SO_CMND   nvarchar2(12) 
	DCNDT_NGAY_CAP number(200) 
	DCNDT_NOI_CAP   nvarchar2(2) 
	DCNDT_MS_THUE   nvarchar2(10) 
	DCNDT_SO_TAI_KHOAN   nvarchar2(30) 
	DCNDT_NGAN_HANG   nvarchar2(400) 
	DCNDT_DIA_CHI_CQ   nvarchar2(400) 
	DCNDT_DIEN_THOAI   nvarchar2(100) 
	DCNDT_EMAIL   nvarchar2(100) 
	NGAY_DANG_KY number(200) 
	TO_CHUC_TAI_TRO_KHAC clob 
	LOCK_TMDT number 
	MUC_CL_SP_DANG_II clob 
	TQ_TINH_HINH_NC clob 
	Y_TUONG_KH clob 
	TAI_LIEU_TK clob 
	NOI_DUNG_NC clob 
	PA_PHOI_HOP clob 
	KQ_NC_SO_KHOI clob 
	MUC_TIEU_NC_EN clob 
	MUC_TIEU_NC_VN clob 
	UD_KQNC_LV_DAO_TAO clob 
	UD_KQNC_SXKD clob 
	UD_KQNC_CHUYEN_GIAO clob 
	PHU_LUC_GIAI_TRINH_LINK   nvarchar2(200) 
	DU_TOAN_LINK   nvarchar2(200) 
	TO_CHUC_TAI_TRO_KHAC_LINK   nvarchar2(200) 
	VB_CHUNG_MINH_VON_KHAC_LINK   nvarchar2(200) 
	THUNG_RAC number 
	FK_TINH_TRANG   nvarchar2(3) 
	FK_BO_MON_DANG_KY   nvarchar2(10) 
	DTB_DANH_GIA number 
	FK_DONG_CHU_NHIEM_HV_NCS   nvarchar2(10) 
	NGAY_UPDATE number(200) 
	DHQG_KP_KHOAN_CHI number 
	DHQG_KP_KHONG_KHOAN_CHI number 
	CTDT_CQ_CONG_TAC   nvarchar2(20) 
	KN_DONG_GOP_DT_1 clob 
	MO_TA_ND_NHAN_SU clob 
	KN_DONG_GOP_DT_2 clob 
	IF_TAP_CHI_QUOC_TE   nvarchar2(200) 
	UD_KQNC_THUC_TE clob 
	UD_KQNC_PHAT_TRIEN_NNC clob 
	FK_MA_HOC_VIEN   nvarchar2(10) 
	FK_MA_KHOA_XET_DUYET   nvarchar2(10)
}

Table KHCN_AN_PHAM_KH_TMDT as APKHTMDT {
  FK_MA_AN_PHAM_KH   nvarchar2(3) [pk]
	FK_MA_THUYET_MINH_DT   nvarchar2(8) [pk]
	SO_LUONG number  
	DK_NOI_CONG_BO   nvarchar2(500)  
	GHI_CHU   nvarchar2(500)  
	TEN_BB_SACH_DK clob  
	TT   nvarchar2(10) 
}

REF: APKHTMDT.FK_MA_AN_PHAM_KH > TMDT.MA_THUYET_MINH_DE_TAI

Table KHCN_CHUYEN_GIA_TMDT as CGTMDT {
  MA_CHUYEN_GIA_TMDT nvarchar2(3) [pk]
	SHCC nvarchar2(10) 
	FK_MA_THUYET_MINH_DT nvarchar2(8) [pk]
	HH_HV_HO_TEN nvarchar2(200) 
	HUONG_NC_CHUYEN_SAU nvarchar2(2000) 
	CO_QUAN_CONG_TAC nvarchar2(200) 
	DIA_CHI nvarchar2(400) 
	DIEN_THOAI nvarchar2(100) 
	EMAIL nvarchar2(100) 
	GHI_CHU nvarchar2(200)
}

REF: CGTMDT.MA_CHUYEN_GIA_TMDT > TMDT.MA_THUYET_MINH_DE_TAI


Table KHCN_CO_QUAN as CQ {
  MA nvarchar2(5) [pk]
	TEN nvarchar2(1000) 
	HO_TEN_TT nvarchar2(100) 
	DIEN_THOAI nvarchar2(50) 
	FAX nvarchar2(50) 
	DIA_CHI nvarchar2(400) 
	EMAIL nvarchar2(100) 
	SO_TAI_KHOAN nvarchar2(30) 
	KHO_BAC nvarchar2(400) 
	GHI_CHU nvarchar2(200) 
}

Table KHCN_CONG_TRINH_KHOA_HOC as CTKH {
  MA_CONG_TRINH nvarchar2(3) [pk] 
	SHCC nvarchar2(10) [pk]
	TEN_TAC_GIA nvarchar2(500) 
	TEN_BAI_BAO nvarchar2(2000) 
	TEN_TAP_CHI nvarchar2(1000) 
	SO_TAP_CHI nvarchar2(100) 
	TRANG_DANG_BAI_BAO nvarchar2(50) 
	NAM_XUAT_BAN_TAP_CHI number 
	LOAI_CONG_TRINH nvarchar2(2) 
	GHI_CHU nvarchar2(1000) 
	ISBN nvarchar2(50) 
	FK_MA_LOAI_TAP_CHI nvarchar2(2) 
	FK_MA_LOAI_TAC_GIA nvarchar2(2) 
	CITY nvarchar2(50) 
	QUOC_GIA nvarchar2(20) 
	NGAY_THANG_XB_TAP_CHI number(200) 
	SAN_PHAM_MA_DE_TAI nvarchar2(1000) 
	DIEM_IF number 
	ISI nvarchar2(50) 
	TAC_GIA_CHINH nvarchar2(200) 
	TAC_GIA_THUOC_VNU nvarchar2(1000) 
	THUOC_LINH_VUC nvarchar2(400) 
	LINK_BAI_BAO nvarchar2(500) 
	TIME_STRAP number(200) 
	LINK_FILE_BAI_BAO nvarchar2(200) 
}

Table KHCN_PB_NOI_DUNG as PB_NOIDUNG
{
    MA_THUYET_MINH_DT NVARCHAR2(8)  [pk]
    SHCC              NVARCHAR2(10) [pk]
    A1_TAM_QUAN_TRONG NVARCHAR2(4000)
    A2_CHAT_LUONG_NC  NVARCHAR2(4000)
    A3_NLNC_CSVC      NVARCHAR2(4000)
    A4_KINH_PHI_NX    NVARCHAR2(4000)
    C_KET_LUAN        NVARCHAR2(4000)
}

table KHCN_PB_DM_NOI_DUNG
{
    MA_ND             NVARCHAR2(20) [pk]
    NOI_DUNG          NVARCHAR2(2000)
    THANG_DIEM_TRUONG NVARCHAR2(50)
    THANG_DIEM_C_NCCB NVARCHAR2(50)
    THANG_DIEM_C_NCUD NVARCHAR2(50)
    THANG_DIEM_C_NCTK NVARCHAR2(50)
}


table KHCN_PB_NOI_DUNG_DANH_GIA
{
    ID                NUMBER [pk]
    MA_THUYET_MINH_DT NVARCHAR2(8)
    SHCC              NVARCHAR2(10)
    STT               NVARCHAR2(8)
    MA_ND             NVARCHAR2(20)
    THANG_DIEM_TRUONG NVARCHAR2(50)
    THANG_DIEM_C_NCCB NVARCHAR2(50)
    THANG_DIEM_C_NCUD NVARCHAR2(50)
    THANG_DIEM_C_NCTK NVARCHAR2(50)
    DIEM              NUMBER
    ID_CHA            NUMBER
    ID_ORDER_BY       NUMBER
    XOA               NUMBER
    CREATE_TIMESTAMP  NUMBER(20)
    UPDATE_TIMESTAMP  NUMBER(20)
    DIEM_TOI_DA       NUMBER
    ALLOW_EDIT        NUMBER
    DIEM_TEXT         NVARCHAR2(50)
}

table KHCN_PB_NOI_DUNG_KINH_PHI
{
    ID                NUMBER [pk]
    MA_THUYET_MINH_DT NVARCHAR2(8)
    SHCC              NVARCHAR2(10)
    STT               NVARCHAR2(8)
    MA_ND             NVARCHAR2(20)
    NHAN_XET          NUMBER
    KINH_PHI_DE_NGHI  NUMBER
    ID_CHA            NUMBER
    ID_ORDER_BY       NUMBER
    XOA               NUMBER
    CREATE_TIMESTAMP  NUMBER(20)
    UPDATE_TIMESTAMP  NUMBER(20)
}

table KHCN_PHAN_CONG_PHAN_BIEN
{
    MA_THUYET_MINH_DT NVARCHAR2(8) [pk]
    SHCC              NVARCHAR2(10) [pk]
    KQ_PHAN_HOI       NUMBER
    NGAY_PHAN_HOI     NUMBER(20)
    NGAY_PHAN_CONG    NUMBER(20)
    GIA_HAN_PB        NUMBER(20)
}

table KHCN_PB_CAU_TRUC
{
    FK_CAP_DE_TAI     NVARCHAR2(2) [pk]
    STT               NUMBER       [pk]
    MA_ND             NVARCHAR2(20)
    NHOM_CHI_TIET     NVARCHAR2(10)
    STT_NHOM_CHI_TIET NVARCHAR2(10)
    ID_ORDER_BY       NUMBER
    MA_ND_CHA         NVARCHAR2(20)
    ALLOW_EDIT        NUMBER
}

Ref: "KHCN_PHAN_CONG_PHAN_BIEN"."MA_THUYET_MINH_DT" < "KHCN_PB_NOI_DUNG"."MA_THUYET_MINH_DT"

Ref: "KHCN_PHAN_CONG_PHAN_BIEN"."SHCC" < "KHCN_PB_NOI_DUNG"."SHCC"

Ref: "KHCN_PB_DM_NOI_DUNG"."MA_ND" < "KHCN_PB_NOI_DUNG_KINH_PHI"."MA_ND"

Ref: "KHCN_PHAN_CONG_PHAN_BIEN"."SHCC" < "KHCN_PB_NOI_DUNG_KINH_PHI"."SHCC"

Ref: "KHCN_PHAN_CONG_PHAN_BIEN"."MA_THUYET_MINH_DT" < "KHCN_PB_NOI_DUNG_KINH_PHI"."MA_THUYET_MINH_DT"

Ref: "KHCN_PHAN_CONG_PHAN_BIEN"."MA_THUYET_MINH_DT" < "KHCN_PB_NOI_DUNG_DANH_GIA"."MA_THUYET_MINH_DT"

Ref: "KHCN_PHAN_CONG_PHAN_BIEN"."SHCC" < "KHCN_PB_NOI_DUNG_DANH_GIA"."SHCC"

Ref: "KHCN_PB_DM_NOI_DUNG"."MA_ND" < "KHCN_PB_NOI_DUNG_DANH_GIA"."MA_ND"

Ref: "KHCN_PB_CAU_TRUC"."MA_ND" < "KHCN_PB_DM_NOI_DUNG"."MA_ND"

Ref: "KHCN_THUYET_MINH_DE_TAI"."MA_THUYET_MINH_DE_TAI" < "KHCN_PHAN_CONG_PHAN_BIEN"."MA_THUYET_MINH_DT"

table KHCN_NHOM_NGANH_TMDT
{
    FK_MA_NHOM_NGANH     NVARCHAR2(3) [pk]
    FK_MA_THUYET_MINH_DT NVARCHAR2(8) [pk]
    TEN_NHOM_NGANH_KHAC  NVARCHAR2(500)
    HUONG_NGHIEN_CUU     NVARCHAR2(1000)
    THU_TU_UU_TIEN       NUMBER
}

table KHCN_CONG_VIEC_PC
{
    ID_CONG_VIEC_PC NVARCHAR2(10) [pk]
	FK_MA_THUYET_MINH_DT NVARCHAR2(8) [not null]
	NOI_DUNG NVARCHAR2(500)
	KQ_KHOA_HOC_TIEU_CHI_DG NVARCHAR2(2000)
	NGUON_NHAN_LUC CLOB
}

table KHCN_DE_TAI_NCKH
{
	MA NVARCHAR2(3) [pk]
	SHCC NVARCHAR2(10) [pk]
	TEN_DE_TAI NVARCHAR2(500)
	NAM_BAT_DAU NUMBER
	NAM_KET_THUC NUMBER
	NGHIEM_THU NUMBER
	CHU_NHIEM NUMBER
	KET_QUA NVARCHAR2(1)
	GHI_CHU NVARCHAR2(100)
	CAP_DE_TAI NVARCHAR2(2)
	TINH_TRANG NUMBER
	MA_SO_DE_TAI NVARCHAR2(50)
	THUOC_CHUONG_TRINH NVARCHAR2(500)
	KINH_PHI NUMBER
	NGAY_NGHIEM_THU NUMBER(20,0)
	TIME_STRAP NUMBER(20,0)
}

table KHCN_DM_KHOAN_CHI_PHI
{
	MA_KHOAN_CHI_PHI NVARCHAR2(3) [pk]
	TEN_KHOAN_CHI_PHI NVARCHAR2(200)
	CAP NVARCHAR2(20)
}

table KHCN_DM_LOAI_SACH
{
	ID NVARCHAR2(2) [pk]
	TEN_LOAI_SACH NVARCHAR2(50) [not null]
	GHI_CHU NVARCHAR2(1000)
}

table KHCN_GIAI_THUONG
{
	SHCC NVARCHAR2(10) [not null]
	TEN_GIAI_THUONG NVARCHAR2(400)
	NOI_DUNG_GIAI_THUONG NVARCHAR2(400)
	NOI_CAP NVARCHAR2(400)
	NUOC_CAP NVARCHAR2(2)
	NAM_CAP NUMBER(4,0)
	TIME NUMBER(20,0)
	MA NUMBER [pk]
	GHI_CHU NVARCHAR2(2000)
	FK_DE_TAI_NCKH NVARCHAR2(3)
}

table KHCN_GT_CHUYEN_GIA
{
	SHCC NVARCHAR2(10) [pk]
	MA_GT_CHUYEN_GIA NVARCHAR2(3) [pk]
	HO_TEN NVARCHAR2(100)
	NOI_CONG_TAC NVARCHAR2(400)
	DIA_CHI_LIEN_LAC NVARCHAR2(400)
	DIEN_THOAI NVARCHAR2(100)
	EMAIL NVARCHAR2(100)
	TIME_STRAP NUMBER(20,0)
}

table KHCN_HD_LUAN_AN
{
    SHCC NVARCHAR2(10) [pk]
	MA_HD_LUAN_AN NVARCHAR2(3) [pk]
	MA_HOC_VIEN NVARCHAR2(10)
	HO_TEN_SV NVARCHAR2(100)
	TEN_LUAN_AN NVARCHAR2(2000)
	NAM_TOT_NGHIEP NUMBER(4,0)
	BAC_DAO_TAO NVARCHAR2(2)
	SAN_PHAM_MA_DE_TAI NVARCHAR2(50)
	TIME NUMBER(20,0)
	TRUONG NVARCHAR2(600)
}

table KHCN_KHA_THI_LLUONG_NCUU
{
    ID_KHA_THI_LLUONG_NCUU NVARCHAR2(10) [pk]
	FK_MA_THUYET_MINH_DT NVARCHAR2(8) [not null]
	NOI_DUNG CLOB
	NANG_LUC_KN_NHOM_NC NVARCHAR2(2000)
	NANG_LUC_KN_DOI_TAC NVARCHAR2(2000)
}

table KHCN_KHA_THI_NVL
{
    ID_KHA_THI_NVL NVARCHAR2(10) [pk]
	FK_MA_THUYET_MINH_DT NVARCHAR2(8) [not null]
	NOI_DUNG NVARCHAR2(500)
}

table KHCN_KHA_THI_NVL_CT
{
    ID_KHA_THI_NVL_CT NVARCHAR2(10) [pk]
	FK_ID_KHA_THI_NVL NVARCHAR2(10) [not null]
	DS_NVL_NANG_LUONG NVARCHAR2(2000)
	NGUON_KINH_PHI NVARCHAR2(200)
}

table KHCN_KHA_THI_TRANG_TBI
{
    ID_KHA_THI_TRANG_TBI NVARCHAR2(10) [pk]
	FK_MA_THUYET_MINH_DT NVARCHAR2(8) [not null]
	NOI_DUNG NVARCHAR2(500)
}

table KHCN_KHA_THI_TRANG_TBI_CT
{
    ID_KHA_THI_TRANG_TBI_CT NVARCHAR2(10) [pk]
	FK_ID_KHA_THI_TRANG_TBI NVARCHAR2(10) [not null]
	DS_THIET_BI NVARCHAR2(1000)
	KN_HUY_DONG_DHQG NVARCHAR2(500)
	KN_HUY_DONG_NO_DHQG NVARCHAR2(500)
}

table KHCN_KINH_NGHIEM_QLDG
{
    SHCC NVARCHAR2(10) [pk]
	MA_KINH_NGHIEM_QLDG NVARCHAR2(3) [pk]
	HINH_THUC_HOI_DONG NVARCHAR2(1000)
	NAM NUMBER
	GHI_CHU NVARCHAR2(200)
	TIME_STRAP NUMBER(20,0)
}

table KHCN_KQ_DAO_TAO_TMDT
{
    FK_BAC_DAO_TAO NVARCHAR2(3) [pk]
	FK_MA_THUYET_MINH_DT NVARCHAR2(8) [pk]
	SO_LUONG NUMBER
	NHIEM_VU_DUOC_GIAO NVARCHAR2(2000)
	DU_KIEN_KINH_PHI NUMBER
	GHI_CHU NVARCHAR2(50)
}

table KHCN_LOGS
{
    SHCC NVARCHAR2(10) [pk]
	LOG_NCKH NVARCHAR2(2000)
	TIME_STRAP NUMBER(20,0)
	NGAY_DUYET NUMBER(20,0)
}

table KHCN_LVNC_KHCN
{
    MA NVARCHAR2(8) [pk]
	TEN NVARCHAR2(500)
	MA_CHA NVARCHAR2(8)
}

table KHCN_LVNC_KHCN_CBGD
{
    SHCC NVARCHAR2(10) [pk]
	FK_MA_LVNC NVARCHAR2(8) [pk]
	LVNC_KHAC NVARCHAR2(500)
	TIME_STRAP NUMBER(20,0)
	NAM NUMBER
}

table KHCN_MUC_TIEU_KINH_TE_XA_HOI
{
    MA NVARCHAR2(5) [pk]
	TEN NVARCHAR2(100)
	MA_CHA NVARCHAR2(5)
}

table KHCN_NGANH_DT
{
    MA_NGANH NVARCHAR2(8) [pk]
	TEN_NGANH NVARCHAR2(200)
	MA_NGANH_CHA NVARCHAR2(6)
	STT NUMBER
	BAC_DAO_TAO NVARCHAR2(3)
}

table KHCN_NHAN_LUC_TMDT_CBGD
{
    MA_NHAN_LUC_TMDT_CBGD NVARCHAR2(3) [pk]
	FK_MA_THUYET_MINH_DT NVARCHAR2(8) [pk]
	HH_HV_HO_TEN NVARCHAR2(200)
	DON_VI_CONG_TAC NVARCHAR2(400)
	SO_THANG_LV_QUY_DOI NUMBER
	SHCC NVARCHAR2(10)
	PHAN_CONG_CHU_TRI_ND NVARCHAR2(1000)
}

table KHCN_NHAN_LUC_TMDT_SV
{
    MA_NHAN_LUC_TMDT_SV NVARCHAR2(3) [pk]
	FK_MA_HOC_VIEN NVARCHAR2(10)
	FK_MA_THUYET_MINH_DT NVARCHAR2(8) [pk]
	SV_HO_TEN NVARCHAR2(200)
	DON_VI_CONG_TAC NVARCHAR2(400)
	SO_THANG_LV_QUY_DOI NUMBER
	GHI_CHU NVARCHAR2(200)
	SHCC NVARCHAR2(10)
	PHAN_CONG_THAM_GIA_ND NVARCHAR2(1000)
}

table KHCN_NHOM_NGANH
{
    MA_NHOM_NGANH NVARCHAR2(3) [pk]
	TEN_NHOM_NGANH NVARCHAR2(400)
	GHI_CHU NVARCHAR2(100)
}

table KHCN_PB_NOI_DUNG_TMP
{
    MA_THUYET_MINH_DT NVARCHAR2(8) [pk]
	SHCC NVARCHAR2(10) [pk]
	A1_TAM_QUAN_TRONG CLOB
	A2_CHAT_LUONG_NC CLOB
	A3_NLNC_CSVC CLOB
	A4_KINH_PHI_NX CLOB
	C_KET_LUAN CLOB
}

table KHCN_PHAN_CONG_CAP_DE_TAI
{
    SHCC NVARCHAR2(6) [pk]
	FK_MA_CAP_DE_TAI NVARCHAR2(3) [pk]
}

table KHCN_SACH
{
    SHCC NVARCHAR2(10) [not null]
	TEN_SACH NVARCHAR2(350)
	NHA_XUAT_BAN NVARCHAR2(150)
	NAM_XUAT_BAN NUMBER
	TAC_GIA NUMBER
	GHI_CHU NVARCHAR2(100)
	SAN_PHAM_MA_DE_TAI NVARCHAR2(50)
	NUOC_NGOAI NUMBER
	BUT_DANH NVARCHAR2(200)
	TIME NUMBER(20,0)
	MA NUMBER [pk]
	FK_LOAI_SACH NVARCHAR2(2)
}

table KHCN_SAN_PHAM_CUNG
{
    MA_SAN_PHAM_CUNG_TMDT NVARCHAR2(3) [pk]
	FK_MA_THUYET_MINH_DT NVARCHAR2(8) [pk]
	TEN_SAN_PHAM_CHI_TIEU CLOB
	DON_VI_DO NVARCHAR2(200)
	CHI_TIEU_DANH_GIA NVARCHAR2(2000)
	MAU_TT_TRONG_NUOC NVARCHAR2(1000)
	MAU_TT_THE_GIOI NVARCHAR2(1000)
	DK_SL_QUY_MO_SP NVARCHAR2(1000)
	GHI_CHU NVARCHAR2(500)
}

table KHCN_SAN_PHAM_MEM
{
    MA_SAN_PHAM_MEM_TMDT NVARCHAR2(3) [pk]
	FK_MA_THUYET_MINH_DT NVARCHAR2(8) [pk]
	TEN_SAN_PHAM NVARCHAR2(2000)
	CHI_TIEU_DANH_GIA NVARCHAR2(2000)
	GHI_CHU NVARCHAR2(500)
}

table KHCN_SO_HUU_TRI_TUE
{
    FK_MA_SO_HUU_TRI_TUE NVARCHAR2(3) [pk]
	FK_MA_THUYET_MINH_DT NVARCHAR2(8) [pk]
	SO_LUONG NUMBER
	NOI_DUNG_DU_KIEN NVARCHAR2(1000)
	GHI_CHU NVARCHAR2(200)
}

table KHCN_TAP_CHI
{
    ID_MA_TAP_CHI NVARCHAR2(5) [pk]
	TEN_TAP_CHI NVARCHAR2(500)
	ISSN NVARCHAR2(50)
	LOAI_TAP_CHI NVARCHAR2(2)
	PHAN_LOAI NVARCHAR2(50)
	MA_CQ_XUAT_BAN NVARCHAR2(5)
	GHI_CHU NVARCHAR2(200)
	E_ISSN NVARCHAR2(50)
	TEN_TAP_CHI_ENG NVARCHAR2(500)
}

table KHCN_TAP_CHI_CT
{
    ID_TAP_CHI_CT NVARCHAR2(10) [pk]
	FK_ID_MA_TAP_CHI NVARCHAR2(5)
	FK_MA_NHOM_NGANH NVARCHAR2(3)
	FK_ID_MA_NGANH NVARCHAR2(10)
	DIEM_CT NUMBER
	GHI_CHU NVARCHAR2(200)
}

table KHCN_TC_CQ_XUAT_BAN
{
    MA NVARCHAR2(5) [pk]
	TEN NVARCHAR2(500)
	DIEM NUMBER
}

table KHCN_TC_NGANH
{
    ID_MA_NGANH NVARCHAR2(10) [pk]
	MA_NGANH NVARCHAR2(10)
	TEN_NGANH NVARCHAR2(500)
	FK_MA_NHOM_NGANH NVARCHAR2(3)
}

table KHCN_TC_NHOM_NGANH
{
    MA_NHOM_NGANH NVARCHAR2(3) [pk]
	TEN_NHOM_NGANH NVARCHAR2(500)
}

table KHCN_THAM_GIA_CHUONG_TRINH
{
    SHCC NVARCHAR2(10) [pk]
	MA_TG_CHUONG_TRINH NVARCHAR2(3) [pk]
	TEN_CHUONG_TRINH NVARCHAR2(400)
	CHUC_DANH NVARCHAR2(200)
	THOI_GIAN_BD NUMBER(4,0)
	NUOC_NGOAI NUMBER
	THOI_GIAN_KT NUMBER(4,0)
	TIME_STRAP NUMBER(20,0)
}

table KHCN_THAM_GIA_HH_TC_HN
{
    SHCC NVARCHAR2(10) [pk]
	MA_TG_HH_TC_HN NVARCHAR2(3) [pk]
	TEN_HH_TC_HN NVARCHAR2(400)
	CHUC_DANH NVARCHAR2(200)
	THOI_GIAN_BD NVARCHAR2(10)
	THOI_GIAN_KT NVARCHAR2(10)
	LOAI NVARCHAR2(2)
	TIME_STRAP NUMBER(20,0)
}

table KHCN_THAM_GIA_TRUONG_VIEN
{
    SHCC NVARCHAR2(10) [pk]
	MA_TG_TRUONG_VIEN NVARCHAR2(3) [pk]
	TEN_TRUONG_VIEN NVARCHAR2(400)
	NOI_DUNG_THAM_GIA NVARCHAR2(1000)
	THOI_GIAN_BD NVARCHAR2(10)
	THOI_GIAN_KT NVARCHAR2(10)
	TIME_STRAP NUMBER(20,0)
}

table KHCN_TONG_HOP_KINH_PHI
{
    FK_MA_KHOAN_CHI_PHI NVARCHAR2(3) [pk]
	FK_MA_THUYET_MINH_DT NVARCHAR2(8) [pk]
	KINH_PHI NUMBER
	KHOAN_CHI NUMBER
	PHAN_TRAM NUMBER
	GHI_CHU NVARCHAR2(300)
	TU_DHQG NUMBER
	TU_NGUON_HUY_DONG NUMBER
}

table DM_AN_PHAM_KH
{
	MA_AN_PHAM_KH NVARCHAR2(20) [pk]
	TEN_AN_PHAM_KH NVARCHAR2(200)
	GHI_CHU NVARCHAR2(200)
	STT NUMBER
	TU_VIET_TAT NVARCHAR2(20)
	FK_MA_CAP_DE_TAI NVARCHAR2(2)
	CAP NUMBER
	DK_NOI_CONG_BO NVARCHAR2(2000)
	FK_MA_AN_PHAM_KH_CHA NVARCHAR2(3)
}

table QT_NGOAI_NGU
{
	SHCC NVARCHAR2(20) [pk]
	MA_NGOAI_NGU NVARCHAR2(3) [pk]
	KY_NANG_NGHE NVARCHAR2(20)
	KY_NANG_NOI NVARCHAR2(20)
	KY_NANG_DOC NVARCHAR2(20)
	KY_NANG_VIET NVARCHAR2(20)
	GHI_CHU NVARCHAR2(200)
	TIME_STRAP NUMBER(20,0)
	KET_QUA NVARCHAR2(50)
}

table KHCN_BANG_SO_HUU_TRI_TUE
{
    SHCC NVARCHAR2(10) [not null]
	TEN_BANG NVARCHAR2(400)
	SAN_PHAM_MA_DE_TAI NVARCHAR2(50)
	SO_HIEU_BANG NVARCHAR2(100)
	NAM_CAP NUMBER
	NOI_CAP NVARCHAR2(400)
	NUOC_CAP NVARCHAR2(2)
	TAC_GIA NUMBER
	TIME NUMBER(20,0)
	MA NUMBER [pk]
	FK_LOAI_TAI_SAN NVARCHAR2(2)
	FK_LINH_VUC NVARCHAR2(8)
}

table TCHC_CAN_BO
{
	SHCC NVARCHAR2(10) [pk]
	TEN NVARCHAR2(30)
	HO NVARCHAR2(100)
	PHAI NVARCHAR2(2)
	DIEN_THOAI NVARCHAR2(20)
	EMAIL NVARCHAR2(50)
	NGAY_SINH NUMBER(20,0)
	NGAY_BAT_DAU_CONG_TAC NUMBER(20,0)
	NGAY_VAO NUMBER(20,0)
	NGAY_CBGD NUMBER(20,0)
	NGAY_BIEN_CHE NUMBER(20,0)
	NGAY_NGHI NUMBER(20,0)
	NGACH NVARCHAR2(6)
	NGACH_MOI NVARCHAR2(20)
	HE_SO_LUONG NUMBER(10,2)
	BAC_LUONG NUMBER(5,0)
	MOC_NANG_LUONG NUMBER(20,0)
	NGAY_HUONG_LUONG NUMBER(20,0)
	TY_LE_VUOT_KHUNG NUMBER(5,0)
	PHU_CAP_CONG_VIEC NUMBER(10,2)
	NGAY_PHU_CAP_CONG_VIEC NUMBER(20,0)
	MA_CHUC_VU NVARCHAR2(3)
	CHUC_VU_BCH_DANG_BO NVARCHAR2(200)
	CHUC_VU_BCH_CONG_DOAN NVARCHAR2(200)
	CHUC_VU_BCH_DOAN_TN NVARCHAR2(200)
	MA_TRINH_DO_LLCT NVARCHAR2(2)
	MA_TRINH_DO_QLNN NVARCHAR2(2)
	MA_TRINH_DO_NN NVARCHAR2(2)
	MA_TRINH_DO_TIN_HOC NVARCHAR2(2)
	HO_KHAU NVARCHAR2(200)
	DIA_CHI_HIEN_TAI NVARCHAR2(200)
	DAN_TOC NVARCHAR2(2)
	TON_GIAO NVARCHAR2(2)
	DANG_VIEN NUMBER(1,0) [not null]
	MA_BO_MON NVARCHAR2(20)
	MA_DON_VI NVARCHAR2(20)
	PHUC_LOI NVARCHAR2(200)
	NHA_GIAO_NHAN_DAN NUMBER(20,0)
	NHA_GIAO_UU_TU NUMBER(20,0)
	DANG_O_NUOC_NGOAI NUMBER(1,0) [not null]
	LY_DO_O_NUOC_NGOAI NVARCHAR2(200)
	GHI_CHU NVARCHAR2(1000)
	MA_XA_NOI_SINH NVARCHAR2(5)
	MA_XA_NGUYEN_QUAN NVARCHAR2(5)
	CMND NVARCHAR2(15)
	NGAY_CAP_CMND NUMBER(20,0)
	NHOM_MAU NVARCHAR2(2)
	NGAY_VAO_DANG NUMBER(20,0)
	NGAY_VAO_DANG_CHINH_THUC NUMBER(20,0)
	NGAY_NHAP_NGU NUMBER(20,0)
	NGAY_XUAT_NGU NUMBER(20,0)
	QUAN_HAM_CAO_NHAT NVARCHAR2(200)
	DANH_HIEU_CAO_NHAT NVARCHAR2(200)
	SO_TRUONG_CONG_TAC NVARCHAR2(200)
	SO_BHXH NVARCHAR2(20)
	HOC_HAM NVARCHAR(3)
	HOC_VI NVARCHAR(3)
	NAM_DAT_HOC_HAM NUMBER
	NAM_DAT_HOC_VI NUMBER
	HOC_VI_CAO_NHAT NVARCHAR(3)
}

table KHCN_DM_LOAI_TAI_SAN
{
	TEN NVARCHAR2(50)
	MA NUMBER [pk]
}